/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-05-13 23:09:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tags/base-page.tag", Long.valueOf(1652480234255L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1652480237996L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.58/webapps/Provisio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProvisioHotels/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Red Team: Anthony Wright Andreas Arnet Angela Perkins Jennifer Thomas Chad Hendren Rusty DeGarmo -->\r\n");
      out.write("<!-- User interface for: About Us/Contact Page-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_ext_005fbase_002dpage_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /about.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("bodyContent");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
        }
        do {
          out.write('\r');
          out.write('\n');
          out.write("\r\n");
          out.write("<section class=\"hero py-6 py-lg-7 text-white dark-overlay\">\r\n");
          out.write("    	<img class=\"bg-image\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/img/photo/aron-visuals-3jBU9TbKW7o-unsplash.jpg\" alt=\"About Provisio Hotels\" />\r\n");
          out.write("		<div class=\"container overlay-content\">\r\n");
          out.write("			<h1 class=\"hero-heading\">About Provisio Hotels</h1>\r\n");
          out.write("		</div>\r\n");
          out.write("	</section>\r\n");
          out.write("\r\n");
          out.write("	<section class=\"hero py-4 py-lg-5\">\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-xl-8 mx-auto\">\r\n");
          out.write("				<p class=\"text-muted\">Provisio Hotels was established in 1984\r\n");
          out.write("					and is proud to have several locations throughout North America. We\r\n");
          out.write("					pride ourselves in offering consistently great experiences by\r\n");
          out.write("					having luxurious, yet attainable, suites with a variety of\r\n");
          out.write("					amenities. Diversity and inclusion is fundamental to our core\r\n");
          out.write("					values and strategic business goals. Taking care of people and\r\n");
          out.write("					their well-being is our guiding principle in all we do.</p>\r\n");
          out.write("				<p class=\"text-muted\">Many of hotels offer fine dining options,\r\n");
          out.write("					swimming pools, and fitness centers, so whether the stay is for\r\n");
          out.write("					work or play, it's always a pleasure!</p>\r\n");
          out.write("				<ul class=\"text-muted fw-light\" style=\"text-align: left;\">\r\n");
          out.write("					<li>Room service is available 24 hours a day</li>\r\n");
          out.write("					<li>You'll find all our rooms provide simple additions to make\r\n");
          out.write("						your stay even easier such as mini-fridges, coffeemakers, and flat\r\n");
          out.write("						screen TVs.</li>\r\n");
          out.write("					<li>Breakfast can be ordered, and is delivered directly to\r\n");
          out.write("						your room.</li>\r\n");
          out.write("					<li>Wi-Fi is available at all locations for a low cost.</li>\r\n");
          out.write("					<li>Parking is available at all locations for a low cost.</li>\r\n");
          out.write("				</ul>\r\n");
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</section>\r\n");
          out.write("\r\n");
          out.write("	<section class=\"hero py-6 py-lg-7 text-white dark-overlay\">\r\n");
          out.write("    	<img class=\"bg-image\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/img/photo/photo-1522143049013-2519756a52d4.jpg\" alt=\"How can we help you today?\" />\r\n");
          out.write("		<div class=\"container overlay-content\">\r\n");
          out.write("			<h1 class=\"hero-heading\">How can we help you today?</h1>\r\n");
          out.write("		</div>\r\n");
          out.write("	</section>\r\n");
          out.write("	");
          out.write("\r\n");
          out.write("	<section class=\"py-6\">\r\n");
          out.write("		<div class=\"container\">\r\n");
          out.write("			<div class=\"row\">\r\n");
          out.write("				<div class=\"col-md-4 text-center text-md-start mb-4 mb-md-0\">\r\n");
          out.write("					<div class=\"icon-rounded mb-4 bg-primary-light\">\r\n");
          out.write("						<i class=\"fa fa-2x text-primary fa-map-marker-alt\"></i>\r\n");
          out.write("					</div>\r\n");
          out.write("					<h3 class=\"h5\">Address</h3>\r\n");
          out.write("					<p class=\"text-muted\">\r\n");
          out.write("						1000 Galvin Rd S<br>Bellevue, NE 68005\r\n");
          out.write("					</p>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"col-md-4 text-center text-md-start mb-4 mb-md-0\">\r\n");
          out.write("					<div class=\"icon-rounded mb-4 bg-primary-light\">\r\n");
          out.write("						<i class=\"fa fa-2x text-primary fa-phone\"></i>\r\n");
          out.write("					</div>\r\n");
          out.write("					<h3 class=\"h5\">Call center</h3>\r\n");
          out.write("					<p class=\"text-muted\">Our call center is available 24 hours a\r\n");
          out.write("						day to assist with reservations, answer questions, and ensure your\r\n");
          out.write("						stay is nothing short of perfection.</p>\r\n");
          out.write("					<p class=\"text-muted\">\r\n");
          out.write("						<strong>1 (800) 535-4028</strong>\r\n");
          out.write("					</p>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"col-md-4 text-center text-md-start mb-4 mb-md-0\">\r\n");
          out.write("					<div class=\"icon-rounded mb-4 bg-primary-light\">\r\n");
          out.write("						<i class=\"fa fa-2x text-primary fa-envelope\"></i>\r\n");
          out.write("					</div>\r\n");
          out.write("					<h3 class=\"h5\">Email Us</h3>\r\n");
          out.write("					<p class=\"text-muted\">Feel free to email Provisio Hotels day or\r\n");
          out.write("						night, we are always at your service.</p>\r\n");
          out.write("					<ul class=\"list-unstyled text-muted\">\r\n");
          out.write("						<li><a\r\n");
          out.write("							href=\"mailto:comments@provisio.com?subject=Comments and Inquires from Provisio.com\">\r\n");
          out.write("								Comments and Inquiries </a></li>\r\n");
          out.write("						<li><a\r\n");
          out.write("							href=\"mailto:support@provisio.com?subject=Technical Support Request Provisio.com\">\r\n");
          out.write("								Technical Support Request </a></li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</section>\r\n");
          out.write("\r\n");
          out.write("	<section class=\"py-6 bg-gray-100\">\r\n");
          out.write("		<div class=\"container\">\r\n");
          out.write("			<h2 class=\"h4 mb-5\">Contact form</h2>\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fset_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			<div class=\"row\">\r\n");
          out.write("				<div class=\"col-md-7 mb-5 mb-md-0\">\r\n");
          out.write("					<form class=\"form\" id=\"contact-form\" method=\"POST\" action=\"\">\r\n");
          out.write("						<div class=\"controls\">\r\n");
          out.write("							<div class=\"row\">\r\n");
          out.write("								<div class=\"col-sm-6\">\r\n");
          out.write("									<div class=\"mb-4\">\r\n");
          out.write("										<label class=\"form-label\" for=\"firstname\">Your firstname *</label>\r\n");
          out.write("										<input class=\"form-control\" type=\"text\" name=\"firstname\" id=\"firstname\" placeholder=\"Enter your firstname\" required>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"col-sm-6\">\r\n");
          out.write("									<div class=\"mb-4\">\r\n");
          out.write("										<label class=\"form-label\" for=\"lastname\">Your lastname*</label> \r\n");
          out.write("										<input class=\"form-control\" type=\"text\" name=\"lastname\" id=\"lastname\" placeholder=\"Enter your  lastname\" required>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"mb-4\">\r\n");
          out.write("								<label class=\"form-label\" for=\"email\">Your email *</label> \r\n");
          out.write("								<input class=\"form-control\" type=\"email\" name=\"email\" id=\"email\" placeholder=\"Enter your  email\" required>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"mb-4\">\r\n");
          out.write("								<label class=\"form-label\" for=\"subject\">Subject *</label> \r\n");
          out.write("								<input class=\"form-control\" type=\"text\" name=\"subject\" id=\"subject\" placeholder=\"Subject\" required>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"mb-4\">\r\n");
          out.write("								<label class=\"form-label\" for=\"message\">Your message for us *</label>\r\n");
          out.write("								<textarea class=\"form-control\" rows=\"4\" name=\"message\" id=\"message\" placeholder=\"Enter your message\" required></textarea>\r\n");
          out.write("							</div>\r\n");
          out.write("							<button class=\"btn btn-outline-primary\" type=\"submit\">Send message</button>\r\n");
          out.write("						</div>\r\n");
          out.write("					</form>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"col-md-5\">\r\n");
          out.write("					<div class=\"ps-lg-4 text-sm\">\r\n");
          out.write("						<p class=\"text-muted\">We're here for you, and always ready to\r\n");
          out.write("							talk. Please provide your contact information and Provisio Hotels\r\n");
          out.write("							will gladly reach out to you. Whether it is a future reservation\r\n");
          out.write("							with some very specific requests, or a past stay that you wish to\r\n");
          out.write("							discuss, we are always happy to hear from you to ensure Provisio\r\n");
          out.write("							Hotels are always your first booking choice.</p>\r\n");
          out.write("\r\n");
          out.write("					</div>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</section>\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f0);
      // /about.jsp(100,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emailDelivered}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"alert alert-success\" role=\"alert\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /about.jsp(101,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emailDelivered}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ext_005fbase_002dpage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  ext:base-page
    org.apache.jsp.tag.web.base_002dpage_tag _jspx_th_ext_005fbase_002dpage_005f0 = new org.apache.jsp.tag.web.base_002dpage_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ext_005fbase_002dpage_005f0);
    try {
      _jspx_th_ext_005fbase_002dpage_005f0.setJspContext(_jspx_page_context);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /about.jsp(154,0) name = title type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setTitle(_jspx_temp0);
      java.lang.String _jspx_temp1 = "margin-top: 72px;";
      // /about.jsp(154,0) name = bodyStyle type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setBodyStyle(_jspx_temp1);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp2 = new Helper( 1, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /about.jsp(154,0) name = header type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setHeader(_jspx_temp2);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp3 = new Helper( 2, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /about.jsp(154,0) name = footer type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setFooter(_jspx_temp3);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp4 = new Helper( 3, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /about.jsp(154,0) name = scripts type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setScripts(_jspx_temp4);
      _jspx_th_ext_005fbase_002dpage_005f0.setJspBody(new Helper( 4, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null));
      _jspx_th_ext_005fbase_002dpage_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ext_005fbase_002dpage_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("About Us");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
      javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("active_nav", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("about", request.getCharacterEncoding()), out, false);
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
      javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke4( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodyContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
          case 4:
            invoke4( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
