/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-05-04 02:11:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.provisio.utils.CurrencyFormatUtil;
import com.provisio.utils.DateFormatUtil;
import com.provisio.models.HotelAmentity;
import java.math.BigDecimal;
import com.provisio.models.Reservation;

public final class reservation_002ddetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tags/base-page.tag", Long.valueOf(1651629371760L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651629376040L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.58/webapps/Provisio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProvisioHotels/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.provisio.models.HotelAmentity");
    _jspx_imports_classes.add("com.provisio.utils.CurrencyFormatUtil");
    _jspx_imports_classes.add("com.provisio.models.Reservation");
    _jspx_imports_classes.add("com.provisio.utils.DateFormatUtil");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Red Team: Anthony Wright Andreas Arnet Angela Perkins Jennifer Thomas Chad Hendren Rusty DeGarmo -->\r\n");
      out.write("<!-- User interface for: Making a new reservation page-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Review reservation details page -->\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /reservation-details.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("bodyContent");
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
          }
          do {
            out.write("\r\n");
            out.write("\r\n");
 

	Reservation res = (Reservation)request.getAttribute("reservation");

	List<HotelAmentity> amts = res.getAmenities();


            out.write("\r\n");
            out.write("\r\n");
            out.write("	<div class=\"container py-5\">\r\n");
            out.write("      <div class=\"row\">\r\n");
            out.write("        <div class=\"col-lg-7\">\r\n");
            out.write("          <div class=\"text-block\">\r\n");
            out.write("            <h1>Reservation: ");
            out.print( res.getCode() );
            out.write("</h1>\r\n");
            out.write("            <p class=\"fw-bold fw-light\">Status: ");
            out.print( res.getStatus() );
            out.write("</p>\r\n");
            out.write("          </div>\r\n");
            out.write("          <div class=\"text-block\">\r\n");
            out.write("            <h6 class=\"mb-4\">");
            out.print( res.getNights() );
            out.write(" nights in ");
            out.print( res.getHotelRoom().getHotel().getName()+", "+res.getHotelRoom().getHotel().getLocation() );
            out.write(" for ");
            out.print( res.getGuests() );
            out.write(" guests</h6>\r\n");
            out.write("            <div class=\"row mb-3\">\r\n");
            out.write("              <div class=\"col-md-6 d-flex align-items-center mb-3 mb-md-0\">\r\n");
            out.write("                <div class=\"date-tile me-3\">\r\n");
            out.write("                  <div class=\"text-uppercase\"> <span class=\"text-sm\">");
            out.print( DateFormatUtil.format(res.getCheckin(), "MMM") );
            out.write("</span><br><strong class=\"text-lg\">");
            out.print( DateFormatUtil.format(res.getCheckin(), "dd") );
            out.write("</strong></div>\r\n");
            out.write("                </div>\r\n");
            out.write("                <p class=\"text-sm mb-0\">");
            out.print( DateFormatUtil.format(res.getCheckin(), "EEEEE") );
            out.write(" check-in</p>\r\n");
            out.write("              </div>\r\n");
            out.write("              <div class=\"col-md-6 d-flex align-items-center\">\r\n");
            out.write("                <div class=\"date-tile me-3\">\r\n");
            out.write("                  <div class=\"text-uppercase\"> <span class=\"text-sm\">");
            out.print( DateFormatUtil.format(res.getCheckout(), "MMM") );
            out.write("</span><br><strong class=\"text-lg\">");
            out.print( DateFormatUtil.format(res.getCheckout(), "dd") );
            out.write("</strong></div>\r\n");
            out.write("                </div>\r\n");
            out.write("                <p class=\"text-sm mb-0\">");
            out.print( DateFormatUtil.format(res.getCheckout(), "EEEEE") );
            out.write(" check-out</p>\r\n");
            out.write("              </div>\r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("          <div class=\"text-block\">\r\n");
            out.write("            <div class=\"row\">\r\n");
            out.write("              <div class=\"col-md-12\">\r\n");
            out.write("                <h6> Room size</h6>\r\n");
            out.write("                <p class=\"text-muted\">");
            out.print( res.getHotelRoom().getRoom().getType() );
            out.write("</p>\r\n");
            out.write("              </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"row\">\r\n");
            out.write("              <div class=\"col-md-12\">\r\n");
            out.write("                <h6> Amenities</h6>\r\n");
            out.write("                <p class=\"text-muted\">                	\r\n");
            out.write("                	");
 
                	
                		if (amts != null && !amts.isEmpty()) {
                			
                			for(HotelAmentity amt : amts) { 
                    			
                    			out.write(amt.getAmentity().getName().concat("<br/>"));
                    		}
                		}

					
            out.write("\r\n");
            out.write("\r\n");
            out.write("				</p>\r\n");
            out.write("              </div>\r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"col-lg-5 ps-xl-5\">\r\n");
            out.write("          <div class=\"card border-0 shadow\">\r\n");
            out.write("            <div class=\"card-body p-4\">\r\n");
            out.write("              <div class=\"text-block pb-3\">\r\n");
            out.write("                <div class=\"d-flex align-items-center\">\r\n");
            out.write("                  <div>\r\n");
            out.write("                    <h6> <a class=\"text-reset\" href=\"detail-rooms.html\">");
            out.print( res.getHotelRoom().getHotel().getName() );
            out.write("</a></h6>\r\n");
            out.write("                    <p class=\"text-muted text-sm mb-0\">");
            out.print( res.getHotelRoom().getHotel().getLocation() );
            out.write("</p>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <a class=\"flex-shrink-0\" href=\"detail-rooms.html\"><img class=\"ms-3 rounded\" src=\"img/photo/photo-1512917774080-9991f1c4c750.jpg\" alt=\"\" width=\"100\"></a>\r\n");
            out.write("                </div>\r\n");
            out.write("              </div>\r\n");
            out.write("              <div class=\"text-block py-3\">\r\n");
            out.write("                <ul class=\"list-unstyled mb-0\">\r\n");
            out.write("                  <li class=\"mb-3\"><i class=\"fas fa-users fa-fw text-muted me-2\"></i>");
            out.print( res.getGuests() );
            out.write(" guests</li>\r\n");
            out.write("                  <li class=\"mb-0\"><i class=\"far fa-calendar fa-fw text-muted me-2\"></i>");
            out.print( DateFormatUtil.format(res.getCheckin()) );
            out.write(" <i class=\"fas fa-arrow-right fa-fw text-muted mx-3\"></i>");
            out.print( DateFormatUtil.format(res.getCheckout()) );
            out.write("</li>\r\n");
            out.write("                </ul>\r\n");
            out.write("              </div>\r\n");
            out.write("              <div class=\"text-block pt-3 pb-0\">\r\n");
            out.write("                <table class=\"w-100\">\r\n");
            out.write("                  <tbody>\r\n");
            out.write("                  \r\n");
            out.write("                  ");

                  			BigDecimal rmPrice = new BigDecimal(0);
                  
                  			if(res.getHotelRoom() != null && res.getHotelRoom().getPrice() != null) {
                  				rmPrice = res.getHotelRoom().getPrice();
                  			}
                  			
                  			int nights = res.getNights();
                  			
                  			BigDecimal lineTot = rmPrice.multiply(BigDecimal.valueOf(nights));
                  
            out.write("\r\n");
            out.write("                  \r\n");
            out.write("                  <tr>\r\n");
            out.write("                    <th class=\"fw-normal py-2\">$");
            out.print( rmPrice );
            out.write(' ');
            out.write('x');
            out.write(' ');
            out.print( nights );
            out.write(" nights</th>\r\n");
            out.write("                    <td class=\"text-end py-2\">$");
            out.print( lineTot );
            out.write("</td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("                  \r\n");
            out.write("                  ");
 
                	
                		if (amts != null && !amts.isEmpty()) {
                			
                			for(HotelAmentity amt : amts) { 
                			Double amtTotalPrice = (amt.getPriceDouble() * nights); 
            out.write("\r\n");
            out.write("                    			\r\n");
            out.write("		         					<tr>\r\n");
            out.write("										<th class=\"fw-normal pt-2 pb-3\">");
            out.print(amt.getAmentity().getName());
            out.write("\r\n");
            out.write("\r\n");
            out.write("											");

											if ((amt.getChargeType().equalsIgnoreCase("per_night"))) {
											
            out.write(' ');
            out.write('(');
            out.write('$');
            out.print(amt.getPriceDouble());
            out.write(" per night)</th>\r\n");
            out.write("										<td class=\"text-end pt-2 pb-3\">$");
            out.print(CurrencyFormatUtil.format(amtTotalPrice));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("										");

										} else {
										
            out.write("\r\n");
            out.write("										(");
            out.print(amt.getChargeType().replace("_", " "));
            out.write(")\r\n");
            out.write("										</th>\r\n");
            out.write("										<td class=\"text-end pt-2 pb-3\">$");
            out.print(amt.getPrice());
            out.write("</td>\r\n");
            out.write("										");

										}
										
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("									</tr>\r\n");
            out.write("                    			\r\n");
            out.write("                 		 ");
   		
			                		}
                			}
						
            out.write("\r\n");
            out.write("					\r\n");
            out.write("                  </tbody>\r\n");
            out.write("                  <tfoot>\r\n");
            out.write("                  <tr class=\"border-top\">\r\n");
            out.write("                    <th class=\"pt-3\">Total</th>\r\n");
            out.write("                    <td class=\"fw-bold text-end pt-3\">$");
            out.print( res.getTotal() );
            out.write("</td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("                  </tfoot>\r\n");
            out.write("                </table>\r\n");
            out.write("              </div>\r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("    </div>\r\n");
            out.write("\r\n");
            int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_ext_005fbase_002dpage_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ext_005fbase_002dpage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  ext:base-page
    org.apache.jsp.tag.web.base_002dpage_tag _jspx_th_ext_005fbase_002dpage_005f0 = new org.apache.jsp.tag.web.base_002dpage_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ext_005fbase_002dpage_005f0);
    try {
      _jspx_th_ext_005fbase_002dpage_005f0.setJspContext(_jspx_page_context);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /reservation-details.jsp(167,0) name = title type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setTitle(_jspx_temp0);
      java.lang.String _jspx_temp1 = "margin-top: 72px;";
      // /reservation-details.jsp(167,0) name = bodyStyle type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setBodyStyle(_jspx_temp1);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp2 = new Helper( 1, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /reservation-details.jsp(167,0) name = header type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setHeader(_jspx_temp2);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp3 = new Helper( 2, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null);
      // /reservation-details.jsp(167,0) name = footer type = null reqTime = true required = false fragment = true deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ext_005fbase_002dpage_005f0.setFooter(_jspx_temp3);
      _jspx_th_ext_005fbase_002dpage_005f0.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_ext_005fbase_002dpage_005f0, null));
      _jspx_th_ext_005fbase_002dpage_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ext_005fbase_002dpage_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("Reservation Info");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
      javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("active_nav", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()), out, false);
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
      javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodyContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
