/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-05-13 22:18:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class base_002dpage_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private javax.servlet.jsp.tagext.JspFragment header;
  private javax.servlet.jsp.tagext.JspFragment footer;
  private javax.servlet.jsp.tagext.JspFragment title;
  private javax.servlet.jsp.tagext.JspFragment styles;
  private javax.servlet.jsp.tagext.JspFragment scripts;
  private java.lang.String bodyStyle;

  public javax.servlet.jsp.tagext.JspFragment getHeader() {
    return this.header;
  }

  public void setHeader(javax.servlet.jsp.tagext.JspFragment header) {
    this.header = header;
    jspContext.setAttribute("header", header);
  }

  public javax.servlet.jsp.tagext.JspFragment getFooter() {
    return this.footer;
  }

  public void setFooter(javax.servlet.jsp.tagext.JspFragment footer) {
    this.footer = footer;
    jspContext.setAttribute("footer", footer);
  }

  public javax.servlet.jsp.tagext.JspFragment getTitle() {
    return this.title;
  }

  public void setTitle(javax.servlet.jsp.tagext.JspFragment title) {
    this.title = title;
    jspContext.setAttribute("title", title);
  }

  public javax.servlet.jsp.tagext.JspFragment getStyles() {
    return this.styles;
  }

  public void setStyles(javax.servlet.jsp.tagext.JspFragment styles) {
    this.styles = styles;
    jspContext.setAttribute("styles", styles);
  }

  public javax.servlet.jsp.tagext.JspFragment getScripts() {
    return this.scripts;
  }

  public void setScripts(javax.servlet.jsp.tagext.JspFragment scripts) {
    this.scripts = scripts;
    jspContext.setAttribute("scripts", scripts);
  }

  public java.lang.String getBodyStyle() {
    return this.bodyStyle;
  }

  public void setBodyStyle(java.lang.String bodyStyle) {
    this.bodyStyle = bodyStyle;
    jspContext.setAttribute("bodyStyle", bodyStyle);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getHeader() != null ) 
      _jspx_page_context.setAttribute("header", getHeader());
    if( getFooter() != null ) 
      _jspx_page_context.setAttribute("footer", getFooter());
    if( getTitle() != null ) 
      _jspx_page_context.setAttribute("title", getTitle());
    if( getStyles() != null ) 
      _jspx_page_context.setAttribute("styles", getStyles());
    if( getScripts() != null ) 
      _jspx_page_context.setAttribute("scripts", getScripts());
    if( getBodyStyle() != null ) 
      _jspx_page_context.setAttribute("bodyStyle", getBodyStyle());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<title>\r\n");
      out.write("		");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getTitle() != null) {
        getTitle().invoke(_jspx_sout);
      }
      out.write(" | Provisio Hotels\r\n");
      out.write("	</title>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Price Slider Stylesheets -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/nouislider/nouislider.css\">\r\n");
      out.write("    <!-- Google fonts - Playfair Display-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700\">\r\n");
      out.write("    <!-- Google fonts - Poppins-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,400i,700\">\r\n");
      out.write("    <!-- swiper-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/css/swiper.min.css\">\r\n");
      out.write("    <!-- Magnigic Popup-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/magnific-popup/magnific-popup.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/css/style.pink.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/css/custom.css\">\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/img/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("	");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getStyles() != null) {
        getStyles().invoke(_jspx_sout);
      }
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodyStyle}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\">\r\n");
      out.write("	\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getHeader() != null) {
        getHeader().invoke(_jspx_sout);
      }
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"position-relative z-index-10 d-print-none\">\r\n");
      out.write("		");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getFooter() != null) {
        getFooter().invoke(_jspx_sout);
      }
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("	<!-- jQuery-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap JS bundle - Bootstrap + PopperJS-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- Magnific Popup - Lightbox for the gallery-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <!-- Smooth scroll-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/smooth-scroll/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap Select-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/bootstrap-select/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("    <!-- Object Fit Images - Fallback for browsers that don't support object-fit-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/vendor/object-fit-images/ofi.min.js\"></script>\r\n");
      out.write("    <!-- Swiper Carousel                       -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/js/swiper.min.js\"></script>\r\n");
      out.write("    <!-- Main Theme JS file    -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initParam.appUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("/js/theme.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("		\r\n");
      out.write("	");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getScripts() != null) {
        getScripts().invoke(_jspx_sout);
      }
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
